services:

  backend:
    container_name: backend-kupi
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '4000:3000'
    depends_on:
      - database
    networks:
      - kp-network
    restart: unless-stopped

  frontend:
    container_name: frontend-kupi
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - backend
    networks:
      - kp-network
    restart: unless-stopped

  database:
    container_name: db-kupi
    image: postgres:12
    env_file:
      - ./backend/.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - kp-network
    restart: unless-stopped

volumes:
  pg-data:

networks:
  kp-network:
    driver: bridge
